added source code
LittleHydron/FindingIntersectionOfTwoArrays pull request #1
Opened 2021-10-28 17:48 UTC by LittleHydron

2021-10-29 09:25 UTC, StasDen requested changes
Great job! But there is something(to my mind) you should change

2021-10-29 09:25 UTC, StasDen commented on main.c
> +const int DIM = 1e5+1;
Why is the number 1e5+1 your restriction?

2021-10-29 09:25 UTC, StasDen commented on main.c
> + *  This function sorts subarray of array <arr> from <leftBorder> to <rightBorder> inclusive using MergeSort algorithm
Why is exactly MergeSort algorithm, not BubbleSort, for instance?

2021-10-29 09:25 UTC, StasDen commented on main.c
> +    int i=leftBorder, j=mid+1, k=leftBorder;
You shuldn't have to use letters such i, j, k(I know it's simpler, but I've got a few troubles while reading)

2021-10-29 09:25 UTC, StasDen commented on main.c
> +    int a[DIM], b[DIM], answer[DIM], tmp[DIM], n, m, k = 0;
What is DIM? https://www.healthline.com/nutrition/dim-supplement

2021-10-29 10:02 UTC, LittleHydron commented on main.c
> +    int a[DIM], b[DIM], answer[DIM], tmp[DIM], n, m, k = 0;
DIM is constant. Maximum allowed size of array

2021-10-29 10:05 UTC, LittleHydron commented on main.c
> + *  This function sorts subarray of array <arr> from <leftBorder> to <rightBorder> inclusive using MergeSort algorithm
MergeSort is one of the fastest sorting algorithms.
BubbleSort is much slower.
MergeSort algorith has O(n*log2(n)) time complexity, while BubbleSort has O(n*n) time complexity.

2021-10-29 10:08 UTC, LittleHydron commented on main.c
> +const int DIM = 1e5+1;
I don't know
Just big constant

2021-10-30 17:14 UTC, LittleHydron commented on main.c
> +    int a[DIM], b[DIM], answer[DIM], tmp[DIM], n, m, k = 0;
DIM for "Dimension" :)

2022-02-21 18:08 UTC, LittleHydron reviewed
Nice work

2022-02-21 18:08 UTC, merged